# Production Docker Compose for CBZify

services:
  cbzify:
    image: ghcr.io/skgchp/cbzify:latest
    container_name: cbzify-prod
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    volumes:
      # Persistent storage for uploads and downloads
      - cbzify-uploads:/app/uploads
      - cbzify-downloads:/app/downloads
    
    environment:
      - FLASK_ENV=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/status')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network configuration
    networks:
      - cbzify-network

volumes:
  cbzify-uploads:
    driver: local
  cbzify-downloads:
    driver: local

networks:
  cbzify-network:
    driver: bridge